### ISSUE TITLE
 hello screen to normal mode after factory reset of ios device

### ISSUE THREAD

**Issue by windowalter** [edwin170/bypassr1n#1]
Please help me in finding a way for  change hello screen to normal mode after factory reset

**Comment by dualra1n** [comment]
> Please help me in finding a way for change hello screen to normal mode after factory reset

downgrade ?, lol you are looking for bypass but this is a downgrade tool

**Comment by onnonn** [comment]
When I use downr1n to downgrade my ipad 2018 which has logout the icloud id in ipados 17.3 to ipados 15.7, and then boot, it still work. But in hello screen, it also need a activate. And then I connect it to wifi, activation failed, use bypassr1n, also failed.

**Comment by edwin170** [comment]
> When I use downr1n to downgrade my ipad 2018 which has logout the icloud id in ipados 17.3 to ipados 15.7, and then boot, it still work. But in hello screen, it also need a activate. And then I connect it to wifi, activation failed, use bypassr1n, also failed.

sooo what's the error of bypassra1n ?
